config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  resources :user, only: [:show] do 
    resources :dive_entries
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dive_entry.rb
class DiveEntry < ApplicationRecord
  belongs_to :diver, :class_name => "User"
  belongs_to :location

  
  validates :diver_id, :location_id, :dive_site, :date, {presence: true}


end 

app/models/dive_entry_photo.rb
class DiveEntryPhoto < ApplicationRecord
  belongs_to :dive_entry
  belongs_to :diver, :class_name => "User"

  validates :dive_photo, :dive_entry_id, presence: true
end

app/models/environmental_study.rb
class EnvironmentalStudy < ApplicationRecord
  has_many :enironmental_study_locations
  has_many :locations, :through => :enironmental_study_locations
  has_many :questions

  validates :study_name, {presence: true}
end

app/models/environmental_study_location.rb
class EnvironmentalStudyLocation < ApplicationRecord
  belongs_to :location
  belongs_to :environmental_study

  validates :location_id, :environmental_study_id, presence: true
 
end

app/models/environmental_study_question.rb
class EnvironmentalStudyQuestion < ApplicationRecord
  belongs_to :environmental_study

  validates :question, :environmental_study_id, presence: true
end

app/models/environmental_study_response.rb
class EnvironmentalStudyResponse < ApplicationRecord
  belongs_to :environmental_study_question
  belongs_to :diver, :class_name => "User"

  validates :response, :survey_question_id, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
has_many :environmental_study_locations
has_many :dive_entries

validates :location_name, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dive_entries, :foreign_key => "diver_id"
  has_many :environmental_study_responses, :foreign_key => "diver_id"
  
  validates :first_name, :last_name, :email, :dive_certification, {presence: true}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def total_time_underwater
    total_time = self.dive_entries.map do |entry|
      entry.dive_time
    end
      total_time.reduce(:+)
  end

  def max_depth
    max_depth = 0
    self.dive_entries.each do |entry|
      if entry.depth > max_depth
        max_depth = entry.depth
      end
    end
    max_depth
  end

  def max_depth_location
    max_depth = 0
    max_depth_dive_site= "N/A"
    max_depth_location = "N/A"
    self.dive_entries.each do |entry|
      if entry.depth > max_depth
        max_depth = entry.depth
        max_depth_dive_site = entry.dive_site
        max_depth_location = entry.location.location_name
      end
    end
    "#{max_depth_dive_site}, #{max_depth_location}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :dive_certification])
  end

  def after_sign_in_path_for(resource)
     user_url(current_user)
  end

end

app/controllers/dive_entries_controller.rb
class DiveEntriesController < ApplicationController
  def index
    @dive_entries = current_user.dive_entries
  end 

  def new
    @dive_entry = DiveEntry.new
  end 

  def create
    @dive_entry = DiveEntry.new(dive_entry_details)
    p @dive_entry
    if @dive_entry.save
      redirect_to user_dive_entries_path
    else
      @errors = @dive_entry.errors.full_messages
      p @errors
      render 'new'
    end
   
  end 



  private

  def dive_entry_params
    params.require(:dive_entry).permit(:dive_site, :date, :dive_time, :depth, :temperature, :visibility, :notes, :location)
  end

  def find_location_id 
    location_id = Location.where(location_name: dive_entry_params[:location])
      if location_id.empty?
        Location.create(location_name: dive_entry_params[:location])
        location_id = Location.all.length
      else
        return location_id.first.id 
      end
    location_id
  end 

  def dive_entry_details
    dive_details = {}
    dive_entry_params.each do |key, value|
      if key != "location"
       dive_details[key] = value
      else 
        dive_details[:location_id] = find_location_id
      end
    end 
    dive_details[:diver_id] = current_user.id
    dive_details
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index



 end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def show
    @total_dives = current_user.dive_entries.length
    @total_time_underwater = current_user.total_time_underwater
    @max_depth = current_user.max_depth
    @max_depth_location = current_user.max_depth_location
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dive_entry_helper.rb
module DiveEntryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dive_entries/edit.html.erb
<h1>edit dive entry</h1>

app/views/dive_entries/index.html.erb
<h1>all dive entries</h1>
<div class=log_book>
  <% current_user.dive_entries.each do |entry|%>
    <div class=primary_entry_data>
      <h2> <%=entry.dive_site %> </h2>
        <ul>
          <li><%= entry.location.location_name %></li>
          <li><%= entry.date%></li>
        </ul>
    </div>
    <div class=secondary_entry_data>
      <ul>
        <li> Dive Time: <%= entry.dive_time %> mins</li>
        <li> Max Depth: <%= entry.depth %> meters</li>
        <li> Temperature: <%= entry.temperature %> degrees</li>
        <li> Visibility: <%= entry.visibility %> meters</li>
        <li> Notes: <%= entry.notes %> </li>
      </ul>
    </div>

  <%end %>
</div>
<div class="add_new_dive_button">
  <%= link_to('Add New Dive', new_user_dive_entry_path) %>
</div>        

app/views/dive_entries/new.html.erb
<h1>New dive entry</h1>
  <%= render '/errors' %>

<div class=new_dive_entry_>
  <%= form_for [@user, @dive_entry], url: user_dive_entries_path do |f| %>
    Dive Site: <%= f.text_field :dive_site %><br />
    Location: <%= f.text_field :location %><br />
    Date: <%= f.date_field :date %><br />
    Dive Time: <%= f.number_field :dive_time %><br />
    Max Depth: <%= f.number_field :depth %><br />
    Temperature: <%= f.number_field :temperature %><br />
    Visibility: <%= f.number_field :visibility %><br />
    Notes: <%= f.text_area :notes %><br />
    <%= f.submit "Save"%>
  <% end %>
</div>

app/views/dive_entries/show.html.erb
<h1>dive entry show page</h1>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

    <div id=vid-section>
       <video id="bgvideo" preload="auto" autoplay="true" loop="loop" muted="muted">
        <source src="video/manta.mp4" type="video/mp4">
        video not supported
      </video>
    </div>


    <div class=logo-section>
      <img src="images/white-cs-logo.png">
    </div>

    <div class=entry-buttons-section>
    <%= render '/login_signin_logout' %>
    </div>


  <div class=about-us-sectino> 
    <h1>About us</h1>
  </div>

   

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CitizenScientist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<h1> <%= current_user.first_name%>'s profile page</h1>
<h2 class=lifetime_stats>Lifetime Dive Stats</h2>
  <ul>
    <li>Number of Dives: <%= @total_dives  %></li>
    <li>Total Time Underwater: <%=  @total_time_underwater %> mins</li>
    <li>Max Depth: <%= @max_depth  %> meters @ <%= @max_depth_location %></li>
  </ul>

<%= link_to('Dive Log', user_dive_entries_path(current_user))  %>